Updates

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,6 +20,8 @@ jobs:
 
   release:
     runs-on: ubuntu-latest
+    needs:
+      - build
     steps:
       - run: |
           if [[ $GITHUB_REF_NAME != release/* ]]; then
@@ -41,10 +43,10 @@ jobs:
             exit 1
           fi
           if [[ $patch != 0 ]]; then
-            prior_version_when_patch="$major.$minor.$((patch - 1))"
+            patched_version="$major.$minor.$((patch - 1))"
           fi
           echo "VERSION=$version" >> $GITHUB_ENV
-          echo "PRIOR_VERSION_WHEN_PATCH=$prior_version_when_patch" >> $GITHUB_ENV
+          echo "PATCHED_VERSION=$patched_version" >> $GITHUB_ENV
 
         # check out main branch to verify there won't be problems with merging the change log
         # at the end of this workflow
@@ -53,7 +55,7 @@ jobs:
           ref: main
 
       - run: |
-          if [[ -z $PRIOR_VERSION_WHEN_PATCH ]]; then
+          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.0 ]]; then
             # not making a patch release
             if ! grep --quiet "^## Version $VERSION " CHANGELOG.md; then
               echo the pull request generated by prepare-release-branch.yml needs to be merged first
@@ -67,88 +69,59 @@ jobs:
       # TODO publish if applicable (e.g. to PyPI)
 
       - name: Generate release notes
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           # conditional block not indented because of the heredoc
-          if [[ ! -z $PRIOR_VERSION_WHEN_PATCH ]]; then
+          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.0 ]]; then
           cat > /tmp/release-notes.txt << EOF
-          This is a patch release on the previous $PRIOR_VERSION_WHEN_PATCH release, fixing the issue(s) below.
+          This is a patch release on the previous $PATCHED_VERSION release, fixing the issue(s) below.
 
           EOF
           fi
 
-          # CHANGELOG_SECTION.md is also used at the end of the release workflow
-          # for copying the change log updates to main
-          sed -n "0,/^## Version $VERSION /d;/^## Version /q;p" CHANGELOG.md \
-            > /tmp/CHANGELOG_SECTION.md
-
           # the complex perl regex is needed because markdown docs render newlines as soft wraps
           # while release notes render them as line breaks
-          perl -0pe 's/(?<!\n)\n *(?!\n)(?![-*] )(?![1-9]+\. )/ /g' /tmp/CHANGELOG_SECTION.md \
+          sed -n "0,/^## Version $VERSION /d;/^## Version /q;p" CHANGELOG.md \
+            | perl -0pe 's/(?<!\n)\n *(?!\n)(?![-*] )(?![1-9]+\. )/ /g' \
             >> /tmp/release-notes.txt
 
       - name: Create GitHub release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          # TODO remove --discussions-category if discussions are not enabled in your repository
+          # TODO check that discussion category "announcements" exists
+          #      or remove --discussions-category if discussions are not enabled in your repository
           gh release create --target $GITHUB_REF_NAME \
                             --title "Version $VERSION" \
                             --notes-file /tmp/release-notes.txt \
                             --discussion-category announcements \
                             v$VERSION
 
+  merge-change-log-to-main:
+    needs:
+      - release
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set environment variables
+        run: |
+          version=$(.github/scripts/get-version.sh)
+          echo "VERSION=$version" >> $GITHUB_ENV
+
+      - name: Copy updated change log section
+        run: |
+          sed -n "0,/^## Version $VERSION /d;/^## Version /q;p" CHANGELOG.md \
+            > /tmp/changelog-section.md
+
       - uses: actions/checkout@v3
         with:
-          # the step below is creating a pull request against main
           ref: main
 
       - name: Copy change log updates to main
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          if [[ -z $PRIOR_VERSION_WHEN_PATCH ]]; then
-            # this was not a patch release, so the version exists already in the CHANGELOG.md
-
-            # update the release date
-            date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
-            sed -Ei "s/## Version $VERSION .*/## Version $VERSION ($date)/" CHANGELOG.md
-
-            # the entries are copied over from the release branch to support workflows
-            # where change log entries may be updated after preparing the release branch
-
-            # copy the portion above the release, up to and including the heading
-            sed -n "0,/^## Version $VERSION ($date)/p" CHANGELOG.md > /tmp/CHANGELOG.md
-
-            # copy the release notes
-            cat /tmp/CHANGELOG_SECTION.md >> /tmp/CHANGELOG.md
-
-            # copy the portion below the release
-            sed -n "0,/^## Version $VERSION /d;0,/^## Version /{/^## Version/!d};p" CHANGELOG.md \
-              >> /tmp/CHANGELOG.md
-
-            # update the real CHANGELOG.md
-            cp /tmp/CHANGELOG.md CHANGELOG.md
-          else
-            # this was a patch release, so the version does not exist already in the CHANGELOG.md
-
-            # copy the portion above the top-most release, not including the heading
-            sed -n "0,/^## Version /{ /^## Version /!p }" CHANGELOG.md > /tmp/CHANGELOG.md
-
-            # add the heading
-            date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
-            echo "## Version $VERSION ($date)" >> /tmp/CHANGELOG.md
-
-            # copy the release notes
-            cat /tmp/CHANGELOG_SECTION.md >> /tmp/CHANGELOG.md
-
-            # copy the portion starting from the top-most release
-            sed -n "/^## Version /,\$p" CHANGELOG.md >> /tmp/CHANGELOG.md
-
-            # update the real CHANGELOG.md
-            cp /tmp/CHANGELOG.md CHANGELOG.md
-          fi
+          release_date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
+          RELEASE_DATE=$release_date .github/scripts/update-change-log-in-main.sh
 
       - name: Use CLA approved github bot
         run: .github/scripts/use-cla-approved-github-bot.sh
@@ -158,16 +131,19 @@ jobs:
           # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
           GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
         run: |
-          message="Copy change log updates from $GITHUB_REF_NAME"
-          body="Copy log updates from \`$GITHUB_REF_NAME\`."
-          branch="opentelemetrybot/copy-change-log-updates-from-${GITHUB_REF_NAME//\//-}"
-
-          if [[ -z $PRIOR_VERSION_WHEN_PATCH ]]; then
-            if git diff --quiet; then
-              echo there are no updates needed to the change log on main, not creating pull request
+          if git diff --quiet; then
+            if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.0 ]]; then
+              echo there are no updates to merge, not creating pull request
               exit 0 # success
+            else
+              echo patch release notes did not get applied for some reason
+              exit 1 # failure
             fi
           fi
+
+          message="Merge change log updates from $GITHUB_REF_NAME"
+          body="Merge log updates from \`$GITHUB_REF_NAME\`."
+          branch="opentelemetrybot/merge-change-log-updates-from-${GITHUB_REF_NAME//\//-}"
 
           git commit -a -m "$message"
           git push origin HEAD:$branch
